### ISSUE TITLE
OPENEUROPA-43: Consolidate theme development workflow

### ISSUE THREAD

**Issue by ademarco** [ec-europa/oe_theme#15]
### Scope
The scope of this ticket is to consolidate the current theme development workflow by:

Integrate new Task Runner
Update ECL to latest version
Setup Docker Compose for frontend compilation tasks with Task Runner

### Tasks
- [ ] New version of ECL running
- [ ] Task Runner setup
- [ ] SASS compilation via Docker

**Comment by ademarco** [comment]
Closing here since we will use related issue on OPENEUROPA board instead.
