### ISSUE TITLE
OPENEUROPA-43: Create Theme Helper module

### ISSUE THREAD

**Issue by ademarco** [ec-europa/oe_theme#17]
### Scope
In Drupal 8 themes capabilities are limited as they cannot expose services or have dependencies on modules.

At the moment the theme depends on the OE Core module while it would be advisable to not create hard dependency at this stage of the project.

We can avoid that by bundling a Theme Helper module within the theme itself, which will have to be enabled when using the theme.

### Tasks
- [ ] Create a OE Theme Helper module and store it in theme's /modules
- [ ] Move ECL Twig loader service declaration from OE Core to OE Theme Helper
- [ ] Make sure that OE Theme does throw an error if the helper module is not enabled

**Comment by ademarco** [comment]
Closing here since we will use related issue on OPENEUROPA board instead.
